/*******************************************************************************
 * Copyright (c) 2015 BSI Business Systems Integration AG.
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Distribution License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/org/documents/edl-v10.html
 *
 * Contributors:
 *     BSI Business Systems Integration AG - initial API and implementation
 ******************************************************************************/
package zodiac.zpt.server.sql;

//tag::createDB[]
//tag::organizationListing[]
public interface SQLs {
  //end::organizationListing[]

 /* String SELECT_TABLE_NAMES = ""
      + "SELECT   UPPER(tablename) "
      + "FROM     sys.systables "
      + "INTO     :result"; // <1>*/

  String HANRILIGHT_CREATE_TABLE = ""
		  + "CREATE   TABLE HANRILIGHT "
		  + "		  (hanrilightid VARCHAR(64) NOT NULL CONSTRAINT HANRILIGHT_PK PRIMARY KEY,"
		  + "          testsite VARCHAR(64), "
		  + "          installdate TIMESTAMP, "
		  + "          installernames VARCHAR(64), "
		  + "          serial VARCHAR(64), "
		  + "          voltage VARCHAR(64), "
		  + "          nichesize VARCHAR(64), "
		  + "          onautomation VARCHAR(64), "
		  + "          runhours VARCHAR(64), "
		  + "          lightcolor VARCHAR(64), "
		  + "          sequencecorrect VARCHAR(64), "
		  + "          waterintrusion VARCHAR(64), "
		  + "          notes VARCHAR(64) "
		  + "          )";
		  
  String TESTSITES_CREATE_TABLE = ""
      + "CREATE   TABLE TESTSITES "
      + "         (siteid VARCHAR(64) NOT NULL CONSTRAINT TESTSITES_PK PRIMARY KEY,"
      + "          lastname VARCHAR(64), "
      + "          firstname VARCHAR(64), "
      + "          street VARCHAR(64), "
      + "          city VARCHAR(64), "
      + "          state VARCHAR(64), "
      + "          zip VARCHAR(64), "
      + "          email VARCHAR(64), "
      + "          phone VARCHAR(64), "
      + "          assignedtech VARCHAR(64), "
      + "          ndaissuedate TIMESTAMP, "
      + "          poolpicurl VARCHAR(512), "
      + "          equippicurl VARCHAR(512), "
      + "          poollayout VARCHAR(64), "
      + "          poolvolume VARCHAR(64), "
      + "          poolshape VARCHAR(64), "
      + "          pooldimensions VARCHAR(64), "
      + "          poolfinish VARCHAR(64), "
      + "          marketingpool VARCHAR(64), "
      + "          eqindooroutdoor VARCHAR(64), "
      + "          eqabovebelowwater VARCHAR(64), "
      + "          servicecontact VARCHAR(64), "
      + "          poolnotes VARCHAR(512), "
      + "          hasautomation VARCHAR(64), "
      + "          automationtype VARCHAR(64), "
      + "          hasiaqualink VARCHAR(64), "
      + "          iaqualinkdevicenumber VARCHAR(64), "
      + "          automationnotes VARCHAR(512), "
      + "          hasinfloors VARCHAR(64), "
      + "          pressuretype VARCHAR(64), "
      + "          suctiontype VARCHAR(64), "
      + "          pressureref BOOLEAN, "
      + "          roboticref BOOLEAN, "
      + "          suctionref BOOLEAN, "
      + "          cleanernotes VARCHAR(512), "
      + "          hassolar VARCHAR(64), "
      + "          gastype VARCHAR(64), "
      + "          heaternotes VARCHAR(512), "
      + "          sitenotes VARCHAR(512) "
      + "         )";

  String TESTSITES_INSERT = ""
	  + "INSERT   INTO "
	  + "TESTSITES  (siteid) "
	  + "VALUES   (:siteId)";
  
  String HANRILIGHT_INSERT = ""
	  + "INSERT   INTO "
	  + "HANRILIGHT  (hanrilightid) "
	  + "VALUES     (:HanriLightId)";
  
  String HANRILIGHT_PAGE_SELECT = ""
		  + "SELECT   hanrilightid, "
		  + "         testsite, "
		  + "         installdate, "
		  + "         installernames, "
		  + "         serial, "
		  + "         voltage, "
		  + "         nichesize, "
		  + "         onautomation, "
		  + "         runhours, "
		  + "         lightcolor, "
		  + "         sequencecorrect, "
		  + "         waterintrusion, "
	      + "         notes "
	      + "FROM     HANRILIGHT ";
  
  String TESTSITES_PAGE_SELECT = ""
	      + "SELECT   siteid, "
	      + "         lastname, "
	      + "         firstname, "
	      + "         street, "
	      + "         city, "
	      + "         state, "
	      + "         zip, "
	      + "         email, "
	      + "         phone, "
	      + "         assignedtech, "
	      + "         ndaissuedate, "
	      + "         poolpicurl, "
	      + "         equippicurl, "
	      + "         poollayout, "
	      + "         poolvolume, "
	      + "         poolshape, "
	      + "         pooldimensions, "
	      + "         poolfinish, "
	      + "         marketingpool, "
	      + "         eqindooroutdoor, "
	      + "         eqabovebelowwater, "
	      + "         servicecontact, "
	      + "         poolnotes, "
	      + "         hasautomation, "
	      + "         automationtype, "
	      + "         hasiaqualink, "
	      + "         iaqualinkdevicenumber, "
	      + "         automationnotes, "
	      + "         hasinfloors, "
	      + "         pressuretype, "
	      + "         suctiontype, "
	      + "         pressureref, "
	      + "         roboticref, "
	      + "         suctionref, "
	      + "         cleanernotes, "
	      + "         hassolar, "
	      + "         gastype, "
	      + "         heaternotes, "
	      + "         sitenotes "
	      + "FROM     TESTSITES ";
  
  String HANRILIGHT_INSERT_SAMPLE = ""
		  + "INSERT  INTO HANRILIGHT "
		  + "        (hanrilightid, "
		  + "         testsite, "
		  + "         installdate, "
		  + "         installernames, "
		  + "         serial, "
		  + "         voltage, "
		  + "         nichesize, "
		  + "         onautomation, "
		  + "         runhours, "
		  + "         lightcolor, "
		  + "         sequencecorrect, "
		  + "         waterintrusion, "
	      + "         notes) ";
  
  String TESTSITES_INSERT_SAMPLE = ""
		  + "INSERT  INTO TESTSITES "
		  + "        (siteid, "
	      + "         lastname, "
	      + "         firstname, "
	      + "         street, "
	      + "         city, "
	      + "         state, "
	      + "         zip, "
	      + "         email, "
	      + "         phone, "
	      + "         assignedtech, "
	      + "         ndaissuedate, "
	      + "         poolpicurl, "
	      + "         equippicurl, "
	      + "         poollayout, "
	      + "         poolvolume, "
	      + "         poolshape, "
	      + "         pooldimensions, "
	      + "         poolfinish, "
	      + "         marketingpool, "
	      + "         eqindooroutdoor, "
	      + "         eqabovebelowwater, "
	      + "         servicecontact, "
	      + "         poolnotes, "
	      + "         hasautomation, "
	      + "         automationtype, "
	      + "         hasiaqualink, "
	      + "         iaqualinkdevicenumber, "
	      + "         automationnotes, "
	      + "         hasinfloors, "
	      + "         pressuretype, "
	      + "         suctiontype, "
	      + "         pressureref, "
	      + "         roboticref, "
	      + "         suctionref, "
	      + "         cleanernotes, "
	      + "         hassolar, "
	      + "         gastype, "
	      + "         heaternotes, "
	      + "         sitenotes) ";
  
  String HANRILIGHT_SELECT = ""
		  + "SELECT   testsite, "
		  + "         installdate, "
		  + "         installernames, "
		  + "         serial, "
		  + "         voltage, "
		  + "         nichesize, "
		  + "         onautomation, "
		  + "         runhours, "
		  + "         lightcolor, "
		  + "         sequencecorrect, "
		  + "         waterintrusion, "
	      + "         notes "
	      + "FROM     HANRILIGHT "
	      + "WHERE    hanrilightid = :HanriLightId "
	      + "INTO     :TestSite, "
		  + "         :InstallDate, "
		  + "         :InstallerNames, "
		  + "         :Serial, "
		  + "         :VoltageGroup, "
		  + "         :NicheSizeBox, "
		  + "         :OnAutomationBox, "
		  + "         :RunHours, "
		  + "         :LightColor, "
		  + "         :SequenceCorrectBox, "
		  + "         :WaterIntrusionBox, "
	      + "         :Notes";
  
  String TESTSITES_SELECT = ""
		  + "SELECT   lastname, "
	      + "         firstname, "
	      + "         street, "
	      + "         city, "
	      + "         state, "
	      + "         zip, "
	      + "         email, "
	      + "         phone, "
	      + "         assignedtech, "
	      + "         ndaissuedate, "
	      + "         poolpicurl, "
	      + "         equippicurl, "
	      + "         poollayout, "
	      + "         poolvolume, "
	      + "         poolshape, "
	      + "         pooldimensions, "
	      + "         poolfinish, "
	      + "         marketingpool, "
	      + "         eqindooroutdoor, "
	      + "         eqabovebelowwater, "
	      + "         servicecontact, "
	      + "         poolnotes, "
	      + "         hasautomation, "
	      + "         automationtype, "
	      + "         hasiaqualink, "
	      + "         iaqualinkdevicenumber, "
	      + "         automationnotes, "
	      + "         hasinfloors, "
	      + "         pressuretype, "
	      + "         suctiontype, "
	      + "         pressureref, "
	      + "         roboticref, "
	      + "         suctionref, "
	      + "         cleanernotes, "
	      + "         hassolar, "
	      + "         gastype, "
	      + "         heaternotes, "
	      + "         sitenotes "
	      + "FROM     TESTSITES "
	      + "WHERE    siteid = :siteId "
	      + "INTO     :LastName, "
	      + "         :FirstName, "
	      + "         :Street, "
	      + "         :City, "
	      + "         :State, "
	      + "         :ZIP, "
	      + "         :Email, "
	      + "         :Phone, "
	      + "         :AssignedTech, "
	      + "         :NDAIssueDate, "
	      + "         :PoolPic.url, "
	      + "         :EquipPic.url, "
	      + "         :PoolLayout, "
	      + "         :PoolVolume, "
	      + "         :PoolShape, "
	      + "         :PoolDimensions, "
	      + "         :PoolFinish, "
	      + "         :MarketingPoolGroup, "
	      + "         :EqIndoorOutdoor, "
	      + "         :EqAboveBelowWater, "
	      + "         :ServiceContact, "
	      + "         :PoolNotes, "
	      + "         :HasAutomation, "
	      + "         :AutomationType, "
	      + "         :HasIAqualink, "
	      + "         :IAqualinkDeviceNumber, "
	      + "         :AutomationNotes, "
	      + "         :HasInfloors, "
	      + "         :PressureType, "
	      + "         :SuctionType, "
	      + "         :PressureRef, "
	      + "         :RoboticRef, "
	      + "         :SuctionRef, "
	      + "         :CleanerNotes, "
	      + "         :HasSolar, "
	      + "         :GasType, "
	      + "         :HeaterNotes, "
	      + "         :SiteNotes";
  
  String HANRILIGHT_UPDATE = ""
		  + "UPDATE   HANRILIGHT "
		  + "SET      testsite = :TestSite, "
		  + "         installdate = :InstallDate, "
		  + "         installernames = :InstallerNames, "
		  + "         serial = :Serial, "
		  + "         voltage = :VoltageGroup, "
		  + "         nichesize = :NicheSizeBox, "
		  + "         onautomation = :OnAutomationBox, "
		  + "         runhours = :RunHours, "
		  + "         lightcolor = :LightColor, "
		  + "         sequencecorrect = :SequenceCorrectBox, "
		  + "         waterintrusion = :WaterIntrusionBox, "
	      + "         notes = :Notes "
	      + "WHERE    hanrilightid = :HanriLightId";
  
  String TESTSITES_UPDATE = ""
	      + "UPDATE   TESTSITES "
	      + "SET      lastname = :LastName, "
	      + "         firstname = :FirstName, "
	      + "         street = :Street, "
	      + "         city = :City, "
	      + "         state = :State, "
	      + "         zip = :ZIP, "
	      + "         email = :Email, "
	      + "         phone = :Phone, "
	      + "         assignedtech = :AssignedTech, "
	      + "         ndaissuedate = :NDAIssueDate, "
	      + "         poolpicurl = :PoolPic.url, "
	      + "         equippicurl = :EquipPic.url, "
	      + "         poollayout = :PoolLayout, "
	      + "         poolvolume = :PoolVolume, "
	      + "         poolshape = :PoolShape, "
	      + "         pooldimensions = :PoolDimensions, "
	      + "         poolfinish = :PoolFinish, "
	      + "         marketingpool = :MarketingPoolGroup, "
	      + "         eqindooroutdoor = :EqIndoorOutdoor, "
	      + "         eqabovebelowwater = :EqAboveBelowWater, "
	      + "         servicecontact = :ServiceContact, "
	      + "         poolnotes = :PoolNotes, "
	      + "         hasautomation = :HasAutomation, "
	      + "         automationtype = :AutomationType, "
	      + "         hasiaqualink = :HasIAqualink, "
	      + "         iaqualinkdevicenumber = :IAqualinkDeviceNumber, "
	      + "         automationnotes = :AutomationNotes, "
	      + "         hasinfloors = :HasInfloors, "
	      + "         pressuretype = :PressureType, "
	      + "         suctiontype = :SuctionType, "
	      + "         pressureref = :PressureRef, "
	      + "         roboticref = :RoboticRef, "
	      + "         suctionref = :SuctionRef, "
	      + "         cleanernotes = :CleanerNotes, "
	      + "         hassolar = :HasSolar, "
	      + "         gastype = :GasType, "
	      + "         heaternotes = :HeaterNotes, "
	      + "         sitenotes = :SiteNotes "
	      + "WHERE    siteid = :siteId";

  String HANRILIGHT_PAGE_DATA_SELECT_INTO = ""
		  + "INTO     :{page.HanriLightId}, "
		  + "         :{page.TestSite}, "
		  + "         :{page.InstallDate}, "
		  + "         :{page.InstallerNames}, "
		  + "         :{page.Serial}, "
		  + "         :{page.VoltageGroup}, "
		  + "         :{page.NicheSizeBox}, "
		  + "         :{page.OnAutomationBox}, "
		  + "         :{page.RunHours}, "
		  + "         :{page.LightColor}, "
		  + "         :{page.SequenceCorrectBox}, "
		  + "         :{page.WaterIntrusionBox}, "
	      + "         :{page.Notes}";
    
  String TESTSITES_PAGE_DATA_SELECT_INTO = ""
		  + "INTO     :{page.siteId}, "
		  + "         :{page.LastName}, "
		  + "         :{page.FirstName}, "
		  + "         :{page.Street}, "
		  + "         :{page.City}, "
		  + "         :{page.State}, "
		  + "         :{page.ZIP}, "
		  + "         :{page.Email}, "
		  + "         :{page.Phone}, "
		  + "         :{page.AssignedTech}, "
		  + "         :{page.NDAIssueDate}, "
		  + "         :{page.PoolPicURL}, "
		  + "         :{page.EquipPicURL}, "
		  + "         :{page.PoolLayout}, "
		  + "         :{page.PoolVolume}, "
		  + "         :{page.PoolShape}, "
		  + "         :{page.PoolDimensions}, "
		  + "         :{page.PoolFinish}, "
		  + "         :{page.MarketingPoolGroup}, "
		  + "         :{page.EqIndoorOutdoor}, "
		  + "         :{page.EqAboveBelowWater}, "
		  + "         :{page.ServiceContact}, "
		  + "         :{page.PoolNotes}, "
		  + "         :{page.HasAutomation}, "
		  + "         :{page.AutomationType}, "
		  + "         :{page.HasIAqualink}, "
		  + "         :{page.IAqualinkDeviceNumber}, "
		  + "         :{page.AutomationNotes}, "
		  + "         :{page.HasInfloors}, "
		  + "         :{page.PressureType}, "
		  + "         :{page.SuctionType}, "
		  + "         :{page.PressureRef}, "
		  + "         :{page.RoboticRef}, "
		  + "         :{page.SuctionRef}, "
		  + "         :{page.CleanerNotes}, "
		  + "         :{page.HasSolar}, "
		  + "         :{page.GasType}, "
		  + "         :{page.HeaterNotes}, "
		  + "         :{page.SiteNotes}";
  
  String HANRILIGHT_VALUES_01 = ""
		  + "VALUES  ('hanrilight01', "
		  + "         'DanLukasik', "
		  + "         '', "
		  + "         'MattGagliano', "
		  + "         's3r1alkhkj', "
		  + "         'Low-12V', "
		  + "         'SpaSize', "
		  + "         'Yes', "
		  + "         '9', "	  
		  + "         'AlpineWhite', "
		  + "         'NoIssue', "
		  + "         'NoIssue', "
		  + "         'Notesnotesnotes')";

  String TESTSITES_VALUES_01 = ""
	  + "VALUES  ('site01', "
	  + "         'Smith', "
	  + "         'Mark', "
	  + "         '4671 Main St', "
	  + "         'Fallbrook', "
	  + "         'CA', "
	  + "         '92118', "
	  + "         'testpool01@zodiac.com', "
	  + "         '9293843737', "	  
	  + "         'Ron Larson', "
	  + "         '2016-01-05 00:00:00', "
	  + "         'https://s-media-cache-ak0.pinimg.com/originals/2a/cd/b1/2acdb1befbdfc968da48e2f64d5a9053.jpg', "
	  + "         'http://www.backyardinnovationstx.com/images/construction-process/step-8.jpg', "
	  + "         'PoolOnly', "
	  + "         '25000', "
	  + "         'Freeform', "
	  + "         '20x28', "
	  + "         'Plaster', "
	  + "         'Yes', "
	  + "         'Outdoors', "
	  + "         'AboveWater', "
	  + "         'Clear Expectations Sam @ 619-888-8888', "
	  + "         'Access around left side. Gate code: 8934', "
	  + "         'Jandy', "
	  + "         'PDA', "
	  + "         'Yes', "
	  + "         'IAQ-342-P34', "
	  + "         'Automation System breaker around right side of equipment pad', "
	  + "         'Yes', "
	  + "         'NoBooster', "
	  + "         'DedicatedLine', "
	  + "         'true', "
	  + "         'false', "
	  + "         'true', "
	  + "         'Extra cleaner bags in shed', "
	  + "         'Yes', "
	  + "         'NaturalGas', "
	  + "         'Heater inside shelter next to eq set', "
	  + "         'General Notes go here')";
  
  String TESTSITES_VALUES_02 = ""
		  + "VALUES  ('site02', "
		  + "         'Jones', "
		  + "         'Ed', "
		  + "         '801 Side St', "
		  + "         'San Diego', "
		  + "         'CA', "
		  + "         '92037', "
		  + "         'jonestestpool02@zodiac.com', "
		  + "         '8583343737', "	  
		  + "         'Matt Gagliano', "
		  + "         '2016-02-07 00:00:00', "
		  + "         'http://simplepooltips.com/wp-content/uploads/2016/01/gas4.jpg', "
		  + "         'https://poolcraft.ca/wp-content/uploads/2015/01/POOL-EQUIPMENT.jpeg', "
		  + "         'PoolSpaCombo', "
		  + "         '20000', "
		  + "         'Rectangle', "
		  + "         '20x40x5', "
		  + "         'ExposedAggregate', "
		  + "         'No', "
		  + "         'Indoors', "
		  + "         'BelowWater', "
		  + "         'SD Pool Service Bill @ 858-888-8888', "
		  + "         '', "
		  + "         'Jandy', "
		  + "         'RS', "
		  + "         'No', "
		  + "         '', "
		  + "         'Automation System breaker around right side of equipment pad', "
		  + "         'No', "
		  + "         'BoosterPump', "
		  + "         'ThroughSkimmer', "
		  + "         'false', "
		  + "         'true', "
		  + "         'false', "
		  + "         'Turn down skimmer valve halfway when using cleaner', "
		  + "         'No', "
		  + "         'Propane', "
		  + "         'If propane runs out call SD Propane @ 343-213-3243 for refill. Owner says order as needed.', "
		  + "         'General Notes here')";
  
  String TESTSITES_VALUES_03 = ""
		  + "VALUES  ('site03', "
		  + "         'Dean', "
		  + "         'James', "
		  + "         '123 Country Ln', "
		  + "         'Louisville', "
		  + "         'KY', "
		  + "         '12435', "
		  + "         'deantestpool03@zodiac.com', "
		  + "         '4933343732', "	  
		  + "         'Desroy Smith', "
		  + "         '2015-06-27 00:00:00', "
		  + "         'https://smedia.webcollage.net/rwvfp/wc/cp/19973657/module/cpwalmart/_cp/products/1422033570306/tab-c21aa757-58eb-48d1-85bc-6e7b5e2ca5d0/d4dca34a-9275-4ccd-a3f7-f40d1db08a9f.jpg.w960.jpg', "
		  + "         'http://cdn2.hubspot.net/hub/87744/file-15819953-jpg/images/typical_equipment_setup.jpg', "
		  + "         'PoolSpaCombo', "
		  + "         '10000', "
		  + "         'Peanut', "
		  + "         '10x20x5', "
		  + "         'Tile', "
		  + "         'Yes', "
		  + "         'Indoors', "
		  + "         'BelowWater', "
		  + "         'No Pool Service', "
		  + "         'Watch for dogs. Keep gates closed.', "
		  + "         'Jandy', "
		  + "         'RS', "
		  + "         'Yes', "
		  + "         'IAQ-003-0023', "
		  + "         'PDA velcroed to wall near equipment', "
		  + "         'No', "
		  + "         'BoosterPump', "
		  + "         'DedicatedLine', "
		  + "         'true', "
		  + "         'true', "
		  + "         'true', "
		  + "         'Plug for robotic near grill', "
		  + "         'Yes', "
		  + "         'NaturalGas', "
		  + "         'Owner picky about running heater too much', "
		  + "         'Windy most days at this site')";
  
  String TESTSITES_VALUES_04 = ""
		  + "VALUES  ('site04', "
		  + "         'Tim', "
		  + "         'Taylor', "
		  + "         '1345 Commerce Dr', "
		  + "         'Vista', "
		  + "         'CA', "
		  + "         '92120', "
		  + "         'ztestpool04@zodiac.com', "
		  + "         '5553343332', "	  
		  + "         'Matt Weening', "
		  + "         '2012-10-10 00:00:00', "
		  + "         'http://i2.cdn.cnn.com/cnnnext/dam/assets/160502155618-terranea-vista-pool-super-169.jpg', "
		  + "         'https://www.penguinpool.com/wp-content/uploads/2012/01/P1020344-Large.jpg', "
		  + "         'SpaOnly', "
		  + "         '5000', "
		  + "         'Square', "
		  + "         '8x8x3', "
		  + "         'Paint', "
		  + "         'Yes', "
		  + "         'Outdoors', "
		  + "         'AboveWater', "
		  + "         'No Pool Service', "
		  + "         'Watch for dogs. Keep gates closed.', "
		  + "         'Jandy', "
		  + "         'RS', "
		  + "         'Yes', "
		  + "         'IAQ-004-0421', "
		  + "         'Automation notes', "
		  + "         'Yes', "
		  + "         'BoosterPump', "
		  + "         'DedicatedLine', "
		  + "         'false', "
		  + "         'true', "
		  + "         'true', "
		  + "         'Nearest outlet in garage', "
		  + "         'No', "
		  + "         'NaturalGas', "
		  + "         'Gas Valve located next to garage door', "
		  + "         'Site notes')";

  String TESTSITES_DROP_TABLE = "DROP TABLE TESTSITES";
  String HANRILIGHT_DROP_TABLE = "DROP TABLE HANRILIGHT";


  // tag::organizationListing[]
  // tag::createDB[]
}
// end::createDB[]
// end::organizationListing[]
